version: '3'

services:
  # PostgreSQL
  database:
    container_name: gobarber-database
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gobarber
    volumes:
      - ./.docker/database_data/:/var/lib/postgresql/data

  # MongoDB
  notifications:
    container_name: gobarber-notifications
    image: mongo:4.4.3
    ports:
      - "27017:27017"

  # Redis
  cache:
    container_name: gobarber-cache
    image: redis:6.0.10-alpine
    ports:
      - "6379:6379"

