version: '3'

services:
  # Server do GoBarber
  # api:
  #   build: .
  #   entrypoint: ./.docker/entrypoint.sh
  #   container_name: gobarber-api
  #   ports:
  #     - 3333:3333
  #   volumes: 
  #     - .:/home/node/app
  #   depends_on: ['database', 'notifications', 'cache']

  # PostgreSQL
  database:
    container_name: gobarber-database
    image: postgres:13.1-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=gobarber
    volumes:
      - ./.docker/database_data/:/var/lib/postgresql/data

  # MongoDB
  notifications:
    container_name: gobarber-notifications
    image: mongo:4.4.3
  
  # Redis
  cache:
    container_name: gobarber-cache
    image: redis:6.0.10-alpine

